// Mocks generated by Mockito 5.4.6 from annotations
// in ddns_updater/test/services/ddns_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ddns_updater/services/ddns_providers/ddns_provider.dart' as _i5;
import 'package:ddns_updater/services/ip_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIpService extends _i1.Mock implements _i2.IpService {
  MockIpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getPublicIp() =>
      (super.noSuchMethod(
            Invocation.method(#getPublicIp, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getPublicIp, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String?> resolveDomainIp(String? domain) =>
      (super.noSuchMethod(
            Invocation.method(#resolveDomainIp, [domain]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [DDNSProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDDNSProvider extends _i1.Mock implements _i5.DDNSProvider {
  MockDDNSProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i3.Future<String> updateIP(String? domain, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateIP, [domain, token]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#updateIP, [domain, token]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String?> getExternalIP() =>
      (super.noSuchMethod(
            Invocation.method(#getExternalIP, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
